apiVersion: v1
kind: Pod

metadata:
  name: backend-pod
  labels:
    app: backend

spec:
  containers:
    - name: backend
      image: kubernetes-anator-app-backend:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000